replace np.float_ with np.float64
to solve the following error

AttributeError: `np.float_` was removed in the NumPy 2.0 release. Use `np.float64` instead.